image:
  file: gitpod.Dockerfile
tasks:
  - name: main
    before: |
      echo $AGE_KEY > $HOME/key.txt
      sh -c "$(curl -fsLS git.io/chezmoi)" -- init --apply $GITPOD_GIT_USER_NAME
    init: |
      echo 'TODO: build project'
    command: |
      echo 'TODO: start app'